#ifndef CONSTANTS_H
#define CONSTANTS_H

#define GET_CPUUSAGE_FAILURE    0xF000
#define GET_MEMORY_FAILURE      0x0F00
#define GET_DISK_R_FAILURE      0x00F0
#define GET_DISK_W_FAILURE      0x000F
#define GET_DATA_FAILURE        0xFFFF0000

#endif // CONSTANTS_H
